export enum MessageType {
    REQUEST_FETCH_SUBTITLE,
    REQUEST_SUMMARIZE,
    REQUEST_START_ASSISTANT,
    REQUEST_STOP_ASSISTANT,
    SUMMARIZE_RESPONSE_STREAM,
    ASSISTANT_RESPONSE_STREAM,
    VIDEO_INFO_UPDATE,
    OPEN_SIDE_PANEL,
}